name: Deploy Movies API

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "MoviesApi/**"
      - "MoviesDemo.sln"
      - ".github/workflows/deploy-api.yml"

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore ./MoviesApi/MoviesApi.csproj

      - name: Build
        run: dotnet build ./MoviesApi/MoviesApi.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./MoviesApi/MoviesApi.csproj --configuration Release --no-build --output ./publish

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: appmhcapieus2
          package: ./publish
          publish-profile: ${{ secrets.API_PUBLISHING_PROFILE }}
